version: "3.7"

services:
  mariadb-node1:
    container_name: mariadb-node1
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - db-network
    volumes:
      - mariadb-node1-data:/var/lib/mysql
      - ./docker_config/galera_cluster1.cnf:/etc/mysql/mariadb.conf.d/60-galera.cnf
      - ./docker_config/init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb-node2:
    container_name: mariadb-node2
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    networks:
      - db-network
    volumes:
      - mariadb-node2-data:/var/lib/mysql
      - ./docker_config/galera_cluster2.cnf:/etc/mysql/mariadb.conf.d/60-galera.cnf
      - ./docker_config/init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql

  maxscale:
    container_name: maxscale
    image: mariadb/maxscale:latest
    ports:
      - "4006:4006"
      - "4008:4008"
      - "8989:8989"
    depends_on:
      - mariadb-node1
      - mariadb-node2
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    networks:
      - db-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - "8080:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    networks:
      - db-network

networks:
  db-network:
    external: true

volumes:
  mariadb-node1-data:
  mariadb-node2-data:
